### ISSUE TITLE
Hey I'm Java Engineer. Not not very familiar with this language

### ISSUE THREAD

**Issue by mushroom11s** [Daniel-Marynicz/GarminIQHRWithZoneDataField#1]
I want development some widgets for my 530, You project can help me learn.😊
But when i clone and build this repo,it can't run with my develop enviroment.
![image](https://user-images.githubusercontent.com/28756933/147333422-69827d6c-0142-4415-a193-39b98fc40aeb.png)
![image](https://user-images.githubusercontent.com/28756933/147333450-e3d90883-2176-42bb-831d-0d432ff2ca58.png)
![image](https://user-images.githubusercontent.com/28756933/147333557-5930b7f0-e3db-4330-9d9d-494ee73c1e3d.png)

Can you help me ,how to handler this problem🙏

**Comment by Daniel-Marynicz** [comment]
You probably need to install sdk and garmin devices in the same versions that are given in the manifest file.
Please read the manifest.xml https://github.com/Daniel-Marynicz/GarminIQHRWithZoneDataField/blob/master/manifest.xml

**Comment by mushroom11s** [comment]
> You probably need to install sdk and garmin devices in the same versions that are given in the manifest file. Please read the manifest.xml https://github.com/Daniel-Marynicz/GarminIQHRWithZoneDataField/blob/master/manifest.xml

Thanks!!!! it's run.😁😁
